version: '3.6'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin-mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_ROOT_DATABASE: root
        MYSQL_USER: user
        MYSQL_PASSWORD: mydb
     
      

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080